## One hot Encoding 

In [2]:
import numpy as np 
import pandas as pd

df = pd.DataFrame({
    'text': ['I love programming', 'students love programming', 'Coding is fun'],
    'output': [1, 1, 0]
})

## Bag of words 

##### Advantages
Simple and intutive
has fixed size 
Captures little bit semantic meaning

##### Disadvantage 
Sparsity -> vector contains lot of zer values 
overfitting 
fils to handle out of vocabulary word
it doesnot consider ordering of words 
It doesnot captures the meaning if small changes in two sentence but have completely different meaning 

ex: D1: this is very good movie
    D2: this is not very good movie

    According to bow both sentence have similar meaning ,because only not is an extra word ,but actually both sentence give opposite meaning so bow fails to capture this 


In [3]:
import pandas as pd
import numpy as np 

In [10]:
df = pd.DataFrame({
    'text': ['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'],
    'output': [1, 1, 0, 0]

})

In [11]:
df

,text,output
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [13]:
bow = cv.fit_transform(df['text'])

In [14]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [16]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [18]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]])

## Bag of n-grams
it will try to capture the meaning of the word by considering n tokens as one word 

example 
D1: people watch campusx
D2: campusx watch campusx
D3: people write comment 
D4: campusx write comment 


if we consider bag of bigrams, then vector will be
    people watch | watch campusx| campux watch | people write| write comment | campusx write 
D1  1|1|0|0|0|0 
D2  0|1|1|0|0|0 
D3  0|0|0|1|1|0 
D4  0|0|0|0|1|1 

Advantage 
Able to capture semantics
easy to implement 

Disadvantage 
dimension of vocabular increases and time complexity increases 
not handles out of vocabulary words



In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))


In [25]:
n_gram_bow = cv.fit_transform(df['text'])


In [26]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [27]:
print(bow.toarray())

[[1 0 1 1 0]
 [2 0 0 1 0]
 [0 1 1 0 1]
 [1 1 0 0 1]]


In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,2))
n_gram_bow = cv.fit_transform(df['text'])
print(cv.vocabulary_)
print(bow.toarray())

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}
[[1 0 1 1 0]
 [2 0 0 1 0]
 [0 1 1 0 1]
 [1 1 0 0 1]]


## TF-IDF (Term Frequency - Inverse document frequency)
Any word occures mor frequently in particular document but other document frequency is very less 
TF(t,d) = (Number of occurences of term t in document d)
        -------------------------------------------------   (Total number of terms in document d)

IDF(t) = log (Total number of documnets in the corpus)
             -----------------------------------------
             (Number of documents with term t in them)

TF ranges from 0-1
Tf-IDF = TF*IDF



=========================
Reason to take log in IDF : to normalize the value 

Example if we have 10000 documents and we have very rare word that only present in 1 document then , IDF without log = 10000, where as with log it will be 4 , if we multiply 10000 with tf , the iDF dominates TF , so to avoid it we are normalizing IDF using log

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [30]:
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [31]:
print(tfidf.idf_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]


In [32]:
print(tfidf.get_feature_names_out())

['campusx' 'comment' 'people' 'watch' 'write']


## Word2VEC

In [36]:
!pip install gensim 

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/23.3 MB ? eta -:--:--
     -------- ------------------------------- 4.7/23.3 MB 27.5 MB/s eta 0:00:01
     --------------------- ----------------- 12.8/23.3 MB 34.1 MB/s eta 0:00:01
     --------------------------------------  23.1/23.3 MB 39.4 MB/s eta 0:00:01
     ---------------------------------------- 23.3/23.3 MB 33.2 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
     ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
     ------------------------- ------------- 10.2/15.8 MB 52.7 MB/s eta 0:00:01
     --------------------------------------  15.7/

  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      + meson setup C:\Users\gayat\AppData\Local\Temp\pip-install-ojl4v8um\scipy_e7f779c7f9d84abe8d71afb9dbe47890 C:\Users\gayat\AppData\Local\Temp\pip-install-ojl4v8um\scipy_e7f779c7f9d84abe8d71afb9dbe47890\.mesonpy-ryb7qgd3 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\gayat\AppData\Local\Temp\pip-install-ojl4v8um\scipy_e7f779c7f9d84abe8d71afb9dbe47890\.mesonpy-ryb7qgd3\meson-python-native-file.ini
      The Meson build system
      Version: 1.9.1
      Source dir: C:\Users\gayat\AppData\Local\Temp\pip-install-ojl4v8um\scipy_e7f779c7f9d84abe8d71afb9dbe47890
      Build dir: C:\Users\gayat\AppData\Local\Temp\pip-install-ojl4v8um\scipy_e7f779c7f9d84abe8d71afb9dbe47890\.mesonpy-ryb7qgd3
      Build type: native build
      Activating VS 17.11.2
      Project name: scipy
      Project version: 1.13.1
      C

In [37]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

ModuleNotFoundError: No module named 'gensim'